version: '2'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - 8080:8080
    volumes:
      - home:/var/jenkins_home

volumes:
  home:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/volumes/jenkins_home

